# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1453cbaac2e3b47eade4536e08fde3ac0aa604299dd3a0f703b99a9a814201679511c2763a31140eb1b1374ba42d53fc3301d607cdcd59ae373519dc53e36cf5

test:
  secret_key_base: a9dff34a5e4013f5a9b8c59e76bd1806db4064f5e20f81c50f8546beff57227af0a3774bebf4b08e1223dea426926f80c97482911bd576fdd758b5a0e71c44af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
